### ISSUE TITLE
Oprava Ganttova diagramu

### ISSUE THREAD

**Issue by chocholkovaj** [word-killers/mark2down#15]
- přidat všechny funkce systému
- předělat časy u testování
- přidat testování u zadavatele (domluvit se s ním na čase..)
- opravit časy, datumy
- přidat sloupec s hodinami
- na konec přidat závěrečnou prezentaci

**Comment by tomasSimandl** [comment]
je potřeba mít testování u zadavatele, když budeme mít automatické testy?
