### ISSUE TITLE
Úprava specifikace požadavků

### ISSUE THREAD

**Issue by LlamaMater** [word-killers/mark2down#3]
1.2 Typografické konvence 
  - vztahuje se k dokumentu specifikace - podobné jako u knih (např. kód je vysázen strojopisem, důležité věci italikou apod.)

___

?.? vztah k projektu, proč
  - důvody vzniku: 
    - špatné verzování u dokumentů typu Word, OpenOffice apod.
    - integrace do jednoho git repozitáře spolu s dokumentovaným projektem
    - snažší na editaci než Word, OO, ..., oddělený styl a obsah - nedochází k "rozbíjení" stylu (př. každý nadpis jiný), lze přizpůsobit styl celého dokumentu

2.3 Třídy uživatelů
  -  malé týmy vývojářů (ca. do 10 lidí), manažeři (?)

2.6 Uživatelská dokumentace
  - online dostupná z editoru (základy syntaxe markdownu, ...), složitější věci jen odkazem na jejich dokumentaci (použití mermaid, ...) 

5.1 Výkonnostní požadavky
  - uživatelsky přijatelná odezva při schopnosti jednoho serveru obsluhovat více uživatelů (bude upřesněno)

5.2 Bezpečnostní požadavky
  - autentifikace uživatelů (OAuth - GitHub), oprávnění k prohlížení/zápisu do repozitáře

5.3 Kvalitativní parametry
  - pokrytí testy >= 80%
  - integrační testy (circle-ci, travis-ci)

___

Upřesňující info e-mailem

**Comment by chocholkovaj** [comment]
Hotovo kromě 5.3
